#ifndef CODEX_LIGHT_BOARD_CONFIG_H
#define CODEX_LIGHT_BOARD_CONFIG_H

#define CODEX_LIGHT_GPIO_GREEN 11u
#define CODEX_LIGHT_GPIO_YELLOW 10u
#define CODEX_LIGHT_GPIO_RED 9u

// Set to 0 for a common-anode module whose LEDs turn on at GPIO LOW.
#define CODEX_LIGHT_ACTIVE_HIGH 1

#define CODEX_LIGHT_BLINK_INTERVAL_MS 400u
#define CODEX_LIGHT_SUCCESS_HOLD_MS 5000u
#define CODEX_LIGHT_LINK_TIMEOUT_MS 60000u

#endif
